config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'restaurants#index'
  resources :reviews, only: [:destroy]
  resources :restaurants do
    resources :reviews, only: [:new, :create]
    collection do
      get :top
    end
    member do
      get :chef
    end
  end
end

# post '/restaurants/:restaurant_id/reviews'
# get '/restaurants/:id/chef', to: 'restaurants#chef'
# get '/restaurants/top', to: 'restaurants#top', as: :top_restaurants
# collection -> when it effects all restaurants
# member     -> when it effects only one restaurant


# See all restaurants -> index
# See details about one restaurant -> show
# Create a restaurant -> new/create
# Update a restaurant
# Destroy a restaurant

# The prefix is ONLY attached to the path
# restaurants_path, method: :post
# restaurant_path(restaurant), method: :patch
# restaurant_path(restaurant), method: :delete

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # Associations
  has_many :reviews # builds a method for us -> daniel.reviews
  belongs_to :user

  # Validations
  validates :name, presence: true
  validates :address, presence: true

  # Geocoding
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant # builds a method review.restaurant
  belongs_to :user
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  # Pundit: white-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    redirect_to(root_path, alert: "You are not authorized to perform this action.")
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :top, :show]

  def top
    @restaurants = policy_scope(Restaurant).where(rating: 5)
    skip_authorization
    # render :top
  end

  def index
    @restaurants = policy_scope(Restaurant) # returns only the restaurants that the user is allowed to see

    @markers = @restaurants.geocoded.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        popup_html: render_to_string(partial: 'restaurants/map_popup', locals: { restaurant: restaurant }),
        marker_html: render_to_string(partial: 'restaurants/map_marker', locals: { restaurant: restaurant })
      }
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant # check if the current_user is allowed to perform this action (show) with the @restaurant
    # ⚠️ `authorize` does not mean we grant access
  end

  def new
    # this instance is for the form
    @restaurant = Restaurant.new
    authorize @restaurant
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user
    authorize @restaurant

    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      # render 'new.html.erb'
      # redirect_to new_restaurant_path
      render :new
    end
  end

  def edit
    # this instance is for the form
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant # the `@restaurant` on the left of the `authorize` is passed as the `record` in the policy
  end
  
  def update
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant

    if @restaurant.update(restaurant_params)
      respond_to do |format|
        format.html { redirect_to restaurant_path(@restaurant) }        
        format.text do
          render partial: 'restaurants/show_content',
                 locals: { restaurant: @restaurant },
                 formats: [:html]
        end
      end
    else
      # if it fails, show the edit form again
      render :edit
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
    @restaurant.destroy
    redirect_to restaurants_path, status: :see_other
  end

  private

  # strong params -> whitelisting the attributes that the user can give us
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(restaurant: @restaurant)
    authorize @review
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.user = current_user
    @review.restaurant = @restaurant
    authorize @review
    if @review.save
      redirect_to restaurant_path(@review.restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    authorize @review
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/application/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/application/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to restaurants_path, class: "navbar-brand" do %>
      <i class="fas fa-utensils"></i>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to "Restaurants", restaurants_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Top', top_restaurants_path, class: "nav-link"  %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Favorites', '#', class: "nav-link"  %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag current_user.avatar_url || "https://kitt.lewagon.com/placeholder/users/trouni", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <h6 class="dropdown-header"><%= current_user.email %></h6>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheSpoon928</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.9.0/mapbox-gl.js"></script>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.9.0/mapbox-gl.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= render 'navbar' %>
    <%= render 'flashes' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheSpoon928</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= render 'navbar' %>
    <%= render 'flashes' %>
    <div class="container">
      <div class="row">
        <div class="col col-md-6 offset-3 p-5">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/restaurants/_card.html.erb
<div class="card-category position-relative mb-2" style="height: 120px; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(http://source.unsplash.com/featured/?<%= restaurant.category %>+food&<%= rand(1000) %>)">
  <%#= image_tag restaurant.user.avatar_url, class: "avatar border position-absolute top-0 end-0 m-2" %>
  <%= restaurant.name %>
  <%= link_to "", restaurant_path(restaurant), class: "card-link"  %>
</div>

app/views/restaurants/_form.html.erb
<%= simple_form_for restaurant,
      html: {
        class: 'd-none',
        data: {
          action: 'submit->side-info#update',
          'side-info-target': "form"
        }
      } do |f| %>
  <%= f.input :name %>
  <%= f.input :address,
    input_html: {data: {address_autocomplete_target: "address"}, class: "d-none" },
    wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
  %>
  <%= f.input :rating %>
  <%= f.input :category %>
  <%= f.submit 'Submit', class: 'btn btn-primary mt-2' %>
<% end %>

app/views/restaurants/_map.html.erb
<div style="width: 100%; height: 100vh;"
  class="position-sticky top-0"
  data-controller="map"
  data-map-markers-value="<%= markers %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
  <%# data-<controller>-<value-name>-value %>
></div>

app/views/restaurants/_map_marker.html.erb
<h5>
  <span class="badge rounded-pill bg-primary border">
    <%= restaurant.chef_name %>
  </span>
</h5>

app/views/restaurants/_map_popup.html.erb
<h4><%= restaurant.name %></h4>
<%= render 'side_info', restaurant: restaurant %>

app/views/restaurants/_show_content.html.erb
<div data-controller="side-info" class="container mt-2">
  <div class="row justify-content-around">
    <div class="col-12 col-sm-8">
      <p>
        <%= link_to '< Restaurants', restaurants_path, class: 'btn-light opacity-25 text-decoration-none' %>
      </p>
      <div class="d-flex align-items-center">
        <h1 class="m-0"><%= @restaurant.name %></h1>
        <p class="m-0 ms-2" style="font-size: 0.8em">
          <% if @restaurant.rating %>
            <% @restaurant.rating.times do %>
              <i class="fas fa-star"></i>
            <% end %>
            <% (5 - @restaurant.rating).times do %>
              <i class="far fa-star"></i>
            <% end %>
          <% else %>
            <i class="far fa-star"></i> No ratings yet
          <% end %>
        </p>
      </div>
      <p class="fw-lighter opacity-75 mt-2"><%= @restaurant.description  %></p>
      <h3>Reviews</h3>
      <ul>
        <% if @restaurant.reviews.any? %>
          <% @restaurant.reviews.each do |review| %>
            <li class="my-5"><%= review.content %> <%= link_to 'x', review_path(review), data: { turbo_method: :delete, turbo_confirm: 'Delete review?' }  %></li>
          <% end %>
        <% else %>
          <p>No reviews yet</p>
          <% if user_signed_in? %>
            <%= link_to 'Be the first to review', new_restaurant_review_path(@restaurant) %>
          <% end %>
        <% end %>
      </ul>
    </div>
    <div class="col-12 col-sm-4 mt-5">
      <%= render 'restaurants/side_info', restaurant: @restaurant %>
    </p>
  </div>
</div>

app/views/restaurants/_side_info.html.erb
<div>
  <p>
    <%= image_tag restaurant.user.avatar_url, class: "avatar" %> <%= restaurant.user.name %>
  </p>
  <div data-side-info-target="details">
    <p class="fw-lighter opacity-75">
      <i class="fas fa-map-pin"></i><span class='ms-2'><%= restaurant.address %></span>
    </p>
    <p class="fw-lighter opacity-75">
      <% rand(2..5).times do %>
        <i class="fas fa-dollar-sign"></i>
      <% end %>
    </p>
    <p class="fw-lighter opacity-75">
      <i class="fas fa-utensils"></i><span class='ms-2'><%= restaurant.category %></span>
    </p>
    <% if user_signed_in? %>
      <div class="d-flex">
        <% if policy(restaurant).edit? %>
          <i data-action="click->side-info#edit" class="fas fa-pencil-alt btn-light mx-1"></i>
        <% end %>
        <% if policy(restaurant).destroy? %>
          <%= link_to restaurant_path(restaurant), data: { turbo_method: :delete, turbo_confirm: "Do you want to delete #{restaurant.name}" } do %>
            <i class="fas fa-trash btn-light mx-1"></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= render 'restaurants/form', restaurant: restaurant %>
</div>

app/views/restaurants/chef.html.erb
<div class="container mt-3">
  <h1><%= @restaurant.chef_name %></h1>
  <p><%= @restaurant.name %></p>
  <p><%= link_to 'Back', restaurant_path(@restaurant)  %></p>
</div>

app/views/restaurants/edit.html.erb
<div class="container">
  <h1>Edit Restaurant</h1>
  <%# <form action="/restaurants" method='post'>
  </form> %>
  <%= render 'restaurants/form', restaurant: @restaurant %>
</div>

app/views/restaurants/index.html.erb
<div class="container-fluid">
  <div class="d-flex justify-content-between align-items-center mt-3">
    <h1>Restaurants</h1>
    <% if policy(Restaurant).new? %>
      <%= link_to new_restaurant_path do %>
        <i class="fas fa-plus-square btn-light"></i>
      <% end %>
    <% end %>
  </div>
  <div class="row">
    <div class="col-12 col-md-4">
      <div class="mb-5">
        <% @restaurants.each do |restaurant| %>
          <%= render 'restaurants/card', restaurant: restaurant %>
        <% end %>
      </div>
    </div>
    <div class="col-12 col-md-8">
      <%= render 'map', markers: @markers.to_json %>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>Add Restaurant</h1>
  <%# <form action="/restaurants" method='post'>
  </form> %>
  <%= render 'restaurants/form' %>
</div>

app/views/restaurants/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(http://source.unsplash.com/featured/?<%= @restaurant.category.downcase %>&<%= rand(1000) %>/800x333);">
  <div class="container">
  </div>
</div>
<%= render 'show_content' %>

app/views/restaurants/top.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center mt-3">
    <h1>Top Restaurants</h1>
    <%= link_to new_restaurant_path do %>
      <i class="fas fa-plus-square btn-light"></i>
    <% end %>
  </div>
  <div class="cards mb-5">
    <% @restaurants.each do |restaurant| %>
      <%= render 'restaurants/card', restaurant: restaurant %>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h1>Add Review</h1>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.submit 'Submit', class: 'btn btn-primary mt-2' %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to restaurants_path, class: "navbar-brand" do %>
      <%= image_tag 'yann.png', class: "avatar" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to "Restaurants", restaurants_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Top', top_restaurants_path, class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/dmbf29", class: "avatar" %>
        </li>
      </ul>
    </div>
  </div>
</div>